version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - gnlow
  ignore:
  - dependency-name: "@types/ws"
    versions:
    - 7.4.0
    - 7.4.1
  - dependency-name: ws
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
  - dependency-name: lodash
    versions:
    - 4.17.20
